### PR TITLE
New: Demo supports now full color animations

### PR DESCRIPTION
**Pull request by c-schmitz**
New: ColorShifter class that helps with shifting an RGB color across an array of colors using a custom step width. Class also supports dimming and brigthening a color.
Dev Some minor fixes the Zirrfa STC color cube class

### CODE REVIEW

**Comment by c-schmitz** [comment]
I am not too firm on the documentation standards yet, so please bear with me. 
Everything else is well tested and confirmed working.

**Comment by MajicDesigns** [comment]
getCurrentColor() declared in header file but not in cpp file.
ColorShifter is in the demo folde - is this a genarally useful class for color handling? Should this be in the main src folder? If so, doc needs to be improved as it will become part of main release. Alternatively, it just gets added to the MD_Cubo class as color specific manipulation methods, or it stays where it is now.

**Comment by MajicDesigns** [comment]
Also, FYI I cleanup up the cpp style (mostly {} usage and indenting) to be consistent with the rest of the library.

**Comment by c-schmitz** [comment]
I think it would makes sense to move ColorShifter to the main src folder, but keep it as a separate class for better overview because it might grow in the future.

Thanks for the cleanup. Hope you are getting your color cube soon - this has been fun.
I really would like to a couple more animations.

I am now thinking of building a 8x8x8 RGB cube and there are several different building instructions - I am just not sure yet which one is within my soldering capabilities (non-SMD) and not too expensive ;).

**Comment by MajicDesigns** [comment]
I'll deal with ColorShifter at some point then. Good luck with your new cube.

**Pull request merged**
